### PR TITLE
fix: v8 deprecations warnings and make module context aware

### LINKED ISSUE #143: address deprecation warnings reported by Node 12+
Node 12 has marked some of these APIs as deprecated:

```
c:\projects\lean-mean-registry-client\src\main.cc(64): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\projects\lean-mean-registry-client\src\main.cc(65): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\projects\lean-mean-registry-client\src\main.cc(66): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\projects\lean-mean-registry-client\src\main.cc(76): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\projects\lean-mean-registry-client\src\main.cc(77): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
c:\projects\lean-mean-registry-client\src\main.cc(78): warning C4996: 'v8::Object::Set': was declared deprecated [C:\projects\lean-mean-registry-client\build\registry.vcxproj]
  c:\users\appveyor\.node-gyp\12.3.1\include\node\v8.h(3358): note: see declaration of 'v8::Object::Set'
```

See https://github.com/atom/node-keytar/pull/186 for a suggested way to migrate to the recommended API, using ` Nan::GetCurrentContext()`

### PR DESCRIPTION
**Pull request by HashimotoYT**
This PR fixes v8 deprecations warnings and makes this module context aware. ~~This use `isolate->GetCurrentContext();` instead of `Nan::GetCurrentContext()` if needed I'm can change to second implementation.~~

Fixes #143

### CODE REVIEW

**Comment by shiftkey** [comment]
> This use `isolate->GetCurrentContext();` instead of `Nan::GetCurrentContext()` if needed I'm can change to second implementation.

I'm fine with `isolate->GetCurrentContext();` 👍

File: src/main.cc [hunk 1]
```diff
@@ -286,11 +288,15 @@ NAN_METHOD(EnumKeys) {
...
-  Nan::SetMethod(exports, "enumKeys", EnumKeys);
+NAN_MODULE_INIT(Init) {
+  Nan::SetMethod(target, "readValues", ReadValues);
+  Nan::SetMethod(target, "enumKeys", EnumKeys);
 }
 
 }
 
+#if NODE_MAJOR_VERSION >= 10
+NAN_MODULE_WORKER_ENABLED(registryNativeModule, Init)
```
Comment (shiftkey) [inline src/main.cc]: @HashimotoYT I actually have a use case coming up where this support will be handy - thanks for adding this!

**Comment by HashimotoYT** [comment]
Looks `.Check()` not implemented in Node < 12, I'm move this to `Nan::GetCurrentContext`
